# Generated by Django 4.2.7 on 2024-01-14 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_categories_product_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='test',
        ),
    ]
