# Generated by Django 4.2.7 on 2024-01-12 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_rename_studentclass_classs_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Classs',
            new_name='Class',
        ),
    ]
