# Generated by Django 4.2.7 on 2024-01-12 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_rename_classs_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='address',
            field=models.TextField(max_length=250, null=True),
        ),
    ]
