# Generated by Django 4.2.7 on 2024-01-12 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_student_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='address',
        ),
    ]
