# Generated by Django 4.2.7 on 2024-01-13 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_remove_student_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='test',
            field=models.TextField(max_length=250, null=True),
        ),
    ]
