# Generated by Django 4.2.7 on 2024-01-13 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_student_test'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='test',
            new_name='address',
        ),
    ]
